version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        patterns:
          - '@biomejs/*'
          - 'typescript'
      development-dependencies:
        patterns:
          - '@types/*'
          - 'semantic-release'
          - '@semantic-release/*'
          - '@alexanderfortin/*'
